import QtQuick 2.2
import Sailfish.Silica 1.0

LicenseBase {
    licenseName: "Public Domain"
    licenseWebsite: "https://www.sqlite.org/copyright.html"

    licenseModel: ListModel {
        ListElement {
            header: true
            text: "SQLite Is Public Domain"
        }

        ListElement {
            text: "All of the code and documentation in SQLite has been dedicated to the public domain by the authors. All code authors, and representatives of the companies they work for, have signed affidavits dedicating their contributions to the public domain and originals of those signed affidavits are stored in a firesafe at the main offices of Hwaci. Anyone is free to copy, modify, publish, use, compile, sell, or distribute the original SQLite code, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means."
        }

        ListElement {
            text: "The previous paragraph applies to the deliverable code and documentation in SQLite - those parts of the SQLite library that you actually bundle and ship with a larger application. Some scripts used as part of the build process (for example the “configure” scripts generated by autoconf) might fall under other open-source licenses. Nothing from these build scripts ever reaches the final deliverable SQLite library, however, and so the licenses associated with those scripts should not be a factor in assessing your rights to copy and use the SQLite library."
        }

        ListElement {
            text: "All of the deliverable code in SQLite has been written from scratch. No code has been taken from other projects or from the open internet. Every line of code can be traced back to its original author, and all of those authors have public domain dedications on file. So the SQLite code base is clean and is uncontaminated with licensed code from other projects."
        }

        ListElement {
            header: true
            text: "Open-Source, not Open-Contribution"
        }

        ListElement {
            text: "SQLite is open-source, meaning that you can make as many copies of it as you want and do whatever you want with those copies, without limitation. But SQLite is not open-contribution. In order to keep SQLite in the public domain and ensure that the code does not become contaminated with proprietary or licensed content, the project does not accept patches from unknown persons."
        }

        ListElement {
            text: "All of the code in SQLite is original, having been written specifically for use by SQLite. No code has been copied from unknown sources on the internet."
        }
    }
}
